//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFridgeFriend
{
    using System;
    
    public enum CategoryEnum : int
    {
        Dairy = 1,
        Meats = 2,
        Seafood = 3,
        Fruits = 4,
        Vegetables = 5,
        GrainsAndCereals = 6,
        LegumesAndNuts = 7,
        Eggs = 8,
        FatsAndOils = 9,
        SweetsAndSnacks = 10,
        SpicesAndHerbs = 11,
        Beverages = 12,
        CondimentsAndSauces = 13,
        BakingIngredients = 14
    }
}
