//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFridgeFriend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public int ActiveQuantity { get; set; }
        public Nullable<int> MinimumQuantity { get; set; }
        public string UnitOfMeasurement { get; set; }
        public System.DateTime DateOfExpiry { get; set; }
        public int StorageLocationId { get; set; }
        public Nullable<CategoryEnum> Category { get; set; }
        public int ImageId { get; set; }
        public string UPC { get; set; }
        public string Notes { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual StorageLocation StorageLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
